### ISSUE TITLE
requirements.txt

### ISSUE THREAD

**Issue by haveeshg** [Akila-Ayanthi/Face-Attribute-Prediction-Model#1]
Hi, trying to use your code. could you also provide the package versions you used. requirements.txt file. Does  this code work with tensorflow 2.0?

**Comment by Akila-Ayanthi** [comment]
Hi, I did this on google colab. So, I used whatever package versions that were provided by them and yes it worked with TF 2.0.

**Comment by haveeshg** [comment]
I see. Thanks for your reply :)
